# -*- coding: utf-8 -*-
"""latihandataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kcKFTaKfbufb_wTQDJ1BFgzgGlYAFZhw
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_excel('shooping_demo.xls')

data.head()

data.shape

data['Buy'].value_counts()

PYes = 41/50
PNo = 9/50

print(PYes)

print(PNo)

pd.crosstab(data['Day'], data['Buy'])

PHolidayNo = 6/9
PWeekdayNo = 2/9
PWeekendNo = 1/9

PHolidayYes = 18/41
PWeekdayYes = 9/41
PWeekendYes = 14/41

PHoliday = 24/50
PWeekday = 11/50
PWeekend = 15/50

print(PWeekdayYes)

# P(A|B) ?
# P(B) = PWeekday
# P(A) = No Buy
# P(B|A)= PWeekday/No = Buy

PNoWeekday = (PWeekdayNo*PNo)/PWeekday
print(PNoWeekday)

PYesWeekday = (PWeekdayYes*PYes)/PWeekday
print(PYesWeekday)

# Probabilitas (Buy | Weekday) > dibanding dengan probabilitas (NoBuy | Weekday)
print(PNoWeekday)
print(PYesWeekday)

# Kondisi B dimana
# Day = Holiday
# Discount = Yes
# Free Delivery = Yes
# A = Buy
# P (A|B) = P(Buy|DiscountYes, Free Delivery Yes, PDayHoliday)

pd.crosstab(data['Discount'], data['Buy'])

PNoDiscountNo = 5/9
PYesDiscountNo = 4/9

PNoDiscountYes = 12/41
PYesDiscountYes = 29/41

PNoDiscount = 17/50
PYesDiscount = 33/50

pd.crosstab(data['Free Delivery'], data['Buy'])

PNoFreeDeliveryNo = 4/9
PYesFreeDeliveryNo = 5/9

PNoFreeDeliveryYes = 10/41
PYesFreeDeliveryYes = 31/41

PNoFreeDelivery = 14/50
PYesFreeDelivery = 36/50

# Kondisi B dimana
# Day = Holiday
# Discount = Yes
# Free Delivery = Yes
# P(A) = NoBuy = PNo
# P(B) = PYesDiscount,PYesFreeDelivery,PHoliday
# P(B|A)1 = (PHoliday|No Buy) = PHolidayNo
# P(B|A)2 = (PYesDiscount|No Buy) = PYesDiscountNo
# P(B|A)3 = (PYesFreeDelivery|No Buy) = PYesDeliveryNo
# P(B)1 = PHoliday
# P(B)2 = PYesDiscount
# P(B)3 = PYesDelivery

#ditanyakan P(A|B) ?
#Rumus
# P(A|B) = P(B|A)*P(A)/P(B)

PNoBuy1 = ((PHolidayNo*PYesDiscountNo*PYesFreeDeliveryNo)*PNo)/(PHoliday*PYesDiscount*PYesFreeDelivery)
print(PNoBuy1)

# Kondisi B dimana
# Day = Holiday
# Discount = Yes
# Free Delivery = Yes
# P(A) = Buy = PYes
# P(B) = PYesDiscount,PYesFreeDelivery,PHoliday
# P(B|A)1 = (PHoliday|Buy) = PHolidayYes
# P(B|A)2 = (PYesDiscount|Buy) = PYesDiscountYes
# P(B|A)3 = (PYesFreeDelivery|Buy) = PYesDeliveryYes
# P(B)1 = PHoliday
# P(B)2 = PYesDiscount
# P(B)3 = PYesDelivery

#ditanyakan P(A|B) ?
#Rumus
# P(A|B) = P(B|A)*P(A)/P(B)

PBuy2 = ((PHolidayYes*PYesDiscountYes*PYesFreeDeliveryYes)*PYes)/(PHoliday*PYesDiscount*PYesFreeDelivery)
print(PBuy2)

# probability of No Buy = 0.1247038284075321
# probability of Buy = 0.8103041119102985

PSum = PNoBuy1 + PBuy2
print(PSum)

PBuy = (PBuy2/PSum) *100
print(PBuy)

PNoBuy = (PNoBuy1*PSum) *100
print(PNoBuy)